[toolchain]
anchor_version = "0.30.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
jiagon_credit = "7BtBtDPEe79rvfDpUzBfBSngBtsFvccyQQNRyhtabzC4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm build"
